// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-oGg5pgyaFnFvnio-doON9VgBdDaQUso',
    appId: '1:1092893740042:web:7dc521e6ce0555d44023f3',
    messagingSenderId: '1092893740042',
    projectId: 'chatapptute-cf577',
    authDomain: 'chatapptute-cf577.firebaseapp.com',
    storageBucket: 'chatapptute-cf577.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx0uiW1V1WebXA_jHtPZexODLXVxuInVM',
    appId: '1:1092893740042:android:0e9acf32ed90124c4023f3',
    messagingSenderId: '1092893740042',
    projectId: 'chatapptute-cf577',
    storageBucket: 'chatapptute-cf577.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJsUqwEvBL65qbCMs3ovDwFKVvrOSvSXQ',
    appId: '1:1092893740042:ios:afd195ae317a05864023f3',
    messagingSenderId: '1092893740042',
    projectId: 'chatapptute-cf577',
    storageBucket: 'chatapptute-cf577.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJsUqwEvBL65qbCMs3ovDwFKVvrOSvSXQ',
    appId: '1:1092893740042:ios:afd195ae317a05864023f3',
    messagingSenderId: '1092893740042',
    projectId: 'chatapptute-cf577',
    storageBucket: 'chatapptute-cf577.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-oGg5pgyaFnFvnio-doON9VgBdDaQUso',
    appId: '1:1092893740042:web:83b5f73bc2b9cce34023f3',
    messagingSenderId: '1092893740042',
    projectId: 'chatapptute-cf577',
    authDomain: 'chatapptute-cf577.firebaseapp.com',
    storageBucket: 'chatapptute-cf577.appspot.com',
  );
}
